//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_course_work.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI_course_work.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1200990 {
            get {
                object obj = ResourceManager.GetObject("1200990", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1663549 {
            get {
                object obj = ResourceManager.GetObject("1663549", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _271681 {
            get {
                object obj = ResourceManager.GetObject("271681", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2716811 {
            get {
                object obj = ResourceManager.GetObject("2716811", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39_anime_dance_girl_usagif_title {
            get {
                object obj = ResourceManager.GetObject("_39_anime_dance_girl_usagif_title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _525108 {
            get {
                object obj = ResourceManager.GetObject("525108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6271108 {
            get {
                object obj = ResourceManager.GetObject("6271108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6271146 {
            get {
                object obj = ResourceManager.GetObject("6271146", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _71cX32jS8lL__AC_UF894_1000_QL80_ {
            get {
                object obj = ResourceManager.GetObject("71cX32jS8lL._AC_UF894,1000_QL80_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_to_cart_icon_adding_shopping_cart_well_organized_fully_editable_add_to_cart_icon_adding_shopping_cart_any_use_like_167547952 {
            get {
                object obj = ResourceManager.GetObject("add-to-cart-icon-adding-shopping-cart-well-organized-fully-editable-add-to-cart-i" +
                        "con-adding-shopping-cart-any-use-like-167547952", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_to_cart_icon_adding_shopping_cart_well_organized_fully_editable_add_to_cart_icon_adding_shopping_cart_any_use_like_1675479521 {
            get {
                object obj = ResourceManager.GetObject("add-to-cart-icon-adding-shopping-cart-well-organized-fully-editable-add-to-cart-i" +
                        "con-adding-shopping-cart-any-use-like-1675479521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Almond_Milk_Tea_Feat {
            get {
                object obj = ResourceManager.GetObject("Almond-Milk-Tea-Feat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beverage1 {
            get {
                object obj = ResourceManager.GetObject("beverage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chicken_shawarma_6 {
            get {
                object obj = ResourceManager.GetObject("chicken-shawarma-6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_house_wallpaper_mural_custom_sizes_available_household_wallpaper_maughons_480065_1024x1024 {
            get {
                object obj = ResourceManager.GetObject("coffee-house-wallpaper-mural-custom-sizes-available-household-wallpaper-maughons-" +
                        "480065_1024x1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coffee_rorozoa_3_15 {
            get {
                object obj = ResourceManager.GetObject("coffee_rorozoa_3_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dark_surface_with_blank_space_fast_food_menu {
            get {
                object obj = ResourceManager.GetObject("dark-surface-with-blank-space-fast-food-menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dark_surface_with_blank_space_fast_food_menu1 {
            get {
                object obj = ResourceManager.GetObject("dark-surface-with-blank-space-fast-food-menu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desktop_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("desktop-1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dutch_Colony_Coffee {
            get {
                object obj = ResourceManager.GetObject("Dutch-Colony-Coffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap easy_french_fries_1 {
            get {
                object obj = ResourceManager.GetObject("easy-french-fries-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Falooda_3260_780x1169 {
            get {
                object obj = ResourceManager.GetObject("Falooda-3260-780x1169", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fast_food_dish_blue {
            get {
                object obj = ResourceManager.GetObject("fast-food-dish-blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap front_view_burger_with_french_fries {
            get {
                object obj = ResourceManager.GetObject("front-view-burger-with-french-fries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap front_view_tasty_meat_burger_with_cheese_salad_dark_background__1_ {
            get {
                object obj = ResourceManager.GetObject("front-view-tasty-meat-burger-with-cheese-salad-dark-background (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FullSizeRender_171 {
            get {
                object obj = ResourceManager.GetObject("FullSizeRender 171", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glass_lemonade_12731219 {
            get {
                object obj = ResourceManager.GetObject("glass-lemonade-12731219", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HTB1Vu0LKVXXXXajXVXXq6xXFXXXe {
            get {
                object obj = ResourceManager.GetObject("HTB1Vu0LKVXXXXajXVXXq6xXFXXXe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Indian_But_Not_Indian_Food_feature {
            get {
                object obj = ResourceManager.GetObject("Indian-But-Not-Indian-Food-feature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Indian_But_Not_Indian_Food_feature1 {
            get {
                object obj = ResourceManager.GetObject("Indian-But-Not-Indian-Food-feature1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1291175021_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1291175021-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1310770982_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1310770982-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1317443847_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1317443847-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1317443847_612x6121 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1317443847-612x6121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1366672341_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1366672341-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1442114184_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1442114184-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_542322474_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-542322474-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_694549544_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-694549544-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MPV {
            get {
                object obj = ResourceManager.GetObject("MPV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peakpx {
            get {
                object obj = ResourceManager.GetObject("peakpx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_chris_f_1283219 {
            get {
                object obj = ResourceManager.GetObject("pexels-chris-f-1283219", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_chris_f_12832191 {
            get {
                object obj = ResourceManager.GetObject("pexels-chris-f-12832191", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_pixabay_50594 {
            get {
                object obj = ResourceManager.GetObject("pexels-pixabay-50594", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_food_background_ingredients_dark_design_tile_cooking_products_173209689__1_ {
            get {
                object obj = ResourceManager.GetObject("photo-food-background-ingredients-dark-design-tile-cooking-products-173209689 (1)" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_black_meat_western_food_banner_background_image_194600 {
            get {
                object obj = ResourceManager.GetObject("pngtree-black-meat-western-food-banner-background-image_194600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_black_meat_western_food_banner_background_image_1946001 {
            get {
                object obj = ResourceManager.GetObject("pngtree-black-meat-western-food-banner-background-image_1946001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_business_technology_digital_high_tech_world_background_backgroundtechnology_backgroundhigh_tech_backgroundworld_image_79012 {
            get {
                object obj = ResourceManager.GetObject("pngtree-business-technology-digital-high-tech-world-background-backgroundtechnolo" +
                        "gy-backgroundhigh-tech-backgroundworld-image_79012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_food_food_snack_eating_goods_image_14522 {
            get {
                object obj = ResourceManager.GetObject("pngtree-food-food-snack-eating-goods-image_14522", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_gourmet_japanese_restaurant_sushi_creative_simple_business_poster_design_image_157485 {
            get {
                object obj = ResourceManager.GetObject("pngtree-gourmet-japanese-restaurant-sushi-creative-simple-business-poster-design-" +
                        "image_157485", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap real_simple_mushroom_black_bean_burgers_recipe_0c365277d4294e6db2daa3353d6ff605 {
            get {
                object obj = ResourceManager.GetObject("real-simple-mushroom-black-bean-burgers-recipe-0c365277d4294e6db2daa3353d6ff605", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slice_chicken_nuggets_ketchup_plate_filled_chicken_nuggets_glass_wine_dark_background_vertical_168531423 {
            get {
                object obj = ResourceManager.GetObject("slice-chicken-nuggets-ketchup-plate-filled-chicken-nuggets-glass-wine-dark-backgr" +
                        "ound-vertical-168531423", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_beef_burger_ready_be_served {
            get {
                object obj = ResourceManager.GetObject("top-view-beef-burger-ready-be-served", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_view_beef_burger_ready_be_served1212 {
            get {
                object obj = ResourceManager.GetObject("top-view-beef-burger-ready-be-served1212", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whole_Wheat_Pizza_Dough_Recipe_6 {
            get {
                object obj = ResourceManager.GetObject("Whole-Wheat-Pizza-Dough-Recipe-6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
